```{r predfuncfcm, cache=cacheon}

predfunc <- function(impdata, nomodvars) {
  modvarstmp <- modvarsfcm[!modvarsfcm %in% nomodvars]
  modvarstmpadj <- modvarsfcm[!modvarsfcm %in% c(nomodvars, nomultmodvars)]
  
  # mult

  ormod <- with(impdata, glm(formula(paste0("scream_id == 'Yes' ~ ", paste(modvarstmpadj, collapse = " + "))),
    family = binomial(link = "logit")
  ))

  sormod <- summary(pool(ormod))

  nval <- length(sormod$term)
  preds <- bind_cols(
    Variable = as.character(sormod$term[2:nval]),
    logor = sormod$estimate[2:nval],
    lci = sormod$estimate[2:nval] - global_z05 * sormod$std.error[2:nval],
    uci = sormod$estimate[2:nval] + global_z05 * sormod$std.error[2:nval],
    p = fn(sormod$p.value[2:nval], dig = 3, p = TRUE)
  ) %>%
    mutate(orci = paste0(fn(exp(logor), 2), " (", fn(exp(lci), 2), "-", fn(exp(uci), 2), ")")) %>%
    select(Variable, orci, p)

  # crude
  for (i in seq_along(modvarstmp)) {
    ormoduni <- with(impdata, glm(formula(paste0("scream_id == 'Yes' ~ ", modvarstmp[i])),
      family = binomial(link = "logit")
    ))

    sormoduni <- summary(pool(ormoduni))

    nval <- length(sormoduni$term)
    predsunitmp <- bind_cols(
      Variable = as.character(sormoduni$term[2:nval]),
      logor = sormoduni$estimate[2:nval],
      lci = sormoduni$estimate[2:nval] - global_z05 * sormoduni$std.error[2:nval],
      uci = sormoduni$estimate[2:nval] + global_z05 * sormoduni$std.error[2:nval],
      p = fn(sormoduni$p.value[2:nval], dig = 3, p = TRUE)
    ) %>%
      mutate(orci = paste0(fn(exp(logor), 2), " (", fn(exp(lci), 2), "-", fn(exp(uci), 2), ")")) %>%
      select(Variable, orci, p)

    if (i == 1) {
      predsuni <<- predsunitmp
    } else {
      predsuni <<- bind_rows(predsuni, predsunitmp)
    }
  }

  predall <- full_join(predsuni, preds, by = "Variable")
  colnames(predall) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))
  return(predall)
}
```

```{r predidfcm, cache=cacheon, dependson="predfuncfcm"}

predoverall <- predfunc(impdata = imprsdatalabfcm, nomodvars = "scream_id")

write.xlsx(predoverall, paste0("./output/tabs/predidoverallfcm_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

default_kable(predoverall,
  font_size = 6,
  caption = "Predictors of ID - overall - Consistency analysis with FCM",
  longtable = TRUE,
  escape = TRUE
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

\clearpage

```{r predideffcm, cache=cacheon, dependson="predfuncfcm"}

# ref
impref <- miceadds::subset_datlist(imprsdatalabfcm, subset = c(rsdatalab$shf_ef_cat == "HFrEF"))

predref <- predfunc(impdata = impref, nomodvars = c("shf_ef_cat", "scream_id"))

# mref
impmref <- miceadds::subset_datlist(imprsdatalabfcm, subset = c(rsdatalab$shf_ef_cat == "HFmrEF"))

predmref <- predfunc(impdata = impmref, nomodvars = c("shf_ef_cat", "scream_id"))

# pef
imppef <- miceadds::subset_datlist(imprsdatalabfcm, subset = c(rsdatalab$shf_ef_cat == "HFpEF"))

predpef <- predfunc(impdata = imppef, nomodvars = c("shf_ef_cat", "scream_id"))

predef <- bind_cols(predref, predmref[2:5], predpef[2:5])

colnames(predef) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 6))

write.xlsx(predef, paste0("./output/tabs/predideffcm_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

default_kable(predef,
  font_size = 4,
  caption = "Predictors of ID by EF - Consistency analysis with FCM",
  longtable = TRUE,
  escape = TRUE
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2, "Crude" = 2, "Adjusted" = 2, "Crude" = 2, "Adjusted" = 2)) %>%
  add_header_above(c(" " = 1, "HFrEF" = 4, "HFmrEF" = 4, "HFpEF" = 4)) %>%
  landscape()
```

\clearpage

```{r predidefintfcm, cache=cacheon}

modvarstmp <- modvarsfcm[!modvarsfcm %in% c("shf_ef_cat", "scream_id", nomultmodvars)]

# interactions
ormodnoint <- with(imprsdatalabfcm, glm(formula(paste0("scream_id == 'Yes' ~ ", paste(modvarstmp, collapse = " + "))),
  family = binomial(link = "logit")
))

p <- tibble(modvarstmp, pint = rep(NA, length(modvarstmp)))

for (i in seq_along(modvarstmp)) {
  ormodint <- with(imprsdatalabfcm, glm(formula(paste0("scream_id == 'Yes' ~ shf_ef_cat * ", modvarstmp[i], " + ", paste(modvarstmp, collapse = " + "))),
    family = binomial(link = "logit")
  ))
  int <- D1(ormodint, ormodnoint)

  p[i, 2] <- fn(int$result[4], dig = 3, p = TRUE)
}

colnames(p) <- c("Variable", "p-value for interaction")

write.xlsx(p, paste0("./output/tabs/predidpinteractionfcm_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

default_kable(p,
  font_size = 6,
  caption = "Predictors of ID - p-values for interaction between EF and the respective variables - Consistency analysis with FCM",
  longtable = TRUE,
  escape = TRUE
)
```
