```{r tab1, cache=cacheon}

tab1func <- function(data, stratavar, tabname, xlsname, addoverall = FALSE) {
  tab1 <- print(CreateTableOne(
    vars = tabvars,
    data = data,
    strata = stratavar, 
    addOverall = addoverall
  ),
  missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
  catDigits = 1, contDigits = 1,
  noSpaces = TRUE,
  explain = FALSE
  )

  tab1 <- as_tibble(cbind(var = rownames(tab1), tab1)) %>%
    select(-test) %>%
    select(var, Missing, everything())

  # <= 2016 for iron and fcm
  tab2016 <- print(CreateTableOne(
    vars = c("shf_ferrocarboxymaltosis_priorinc2016", "ddr_ironoralsupp_priorinc2016"),
    data = data %>% filter(shf_indexyear <= 2016),
    strata = stratavar
  ),
  missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
  catDigits = 1, contDigits = 1,
  noSpaces = TRUE,
  explain = FALSE
  )
  tab2016 <- as_tibble(cbind(var = rownames(tab2016), tab2016)) %>%
    select(-test) %>%
    select(var, Missing, everything()) %>%
    filter(var != "n")

  # >= 2017 for iron and fcm
  tab2017 <- print(CreateTableOne(
    vars = c("shf_ferrocarboxymaltosis_postinc2017", "ddr_ironoralsupp_postinc2017", "fcm_ironoral_postinc2017"),
    data = data %>% filter(shf_indexyear >= 2017),
    strata = stratavar
  ),
  missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
  catDigits = 1, contDigits = 1,
  noSpaces = TRUE,
  explain = FALSE
  )
  tab2017 <- as_tibble(cbind(var = rownames(tab2017), tab2017)) %>%
    select(-test) %>%
    select(var, Missing, everything()) %>%
    filter(var != "n")

  # all together
  tab1 <- bind_rows(tab1, tab2016, tab2017)

  tab1 <- tab1 %>%
    # remove = Yes
    mutate(across(everything(), str_replace_all, fixed(" = Yes"), "")) %>%
    # to get labs and units in place
    mutate(
      var_tmp = str_split(var, " = ", simplify = TRUE)[, 1],
      val_tmp = str_split(var, " = ", simplify = TRUE)[, 2],
      # if recoding or categorizing will still get org label
      var_tmp2 = str_replace_all(var_tmp, "(_cat2|_cat)", ""),
      # if shf/sos combination  will still get org label
      var_tmp2 = str_replace_all(var_tmp2, "shf_sos_com_", "sos_com_"),
    )

  tab1 <- left_join(tab1,
    meta.variables.Sheet.1 %>%
      select(variable, label, unit),
    by = c("var_tmp2" = "variable")
  ) %>%
    mutate(
      Variable = coalesce(label, var_tmp),
      Variable = if_else(!is.na(unit),
        paste0(Variable, " (", unit, ")"),
        Variable
      ),
      Variable = if_else(val_tmp != "",
        paste0(Variable, " ", val_tmp),
        Variable
      )
    )


  write.xlsx(tab1 %>%
    select(Variable, Missing:p), paste0("./output/tabs/tab1_", xlsname, "_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

  # footnotes
  tab1 <- tab1 %>%
    mutate(
      footnote1 = if_else(var_tmp %in% modvarsfcm, footnote_marker_symbol(1), ""),
      footnote2 = if_else(str_detect(var, "^scb_dispincome_cat"), footnote_marker_symbol(2), ""),
      footnote3 = if_else(str_detect(var, "^shf_ntprobnp_cat"), footnote_marker_symbol(3), ""),
      footnote4 = if_else(str_detect(var, "priorinc2016|postinc2017"), footnote_marker_symbol(4), ""),
    ) %>%
    unite(footnote, starts_with("footnote"), sep = "") %>%
    mutate(
      # so no probs
      Variable = sanitize_text(Variable),
      Variable = paste0(Variable, footnote),

      # space in Latex output (fix this other way?)
      Variable = sub("  ", ". ", Variable)
    ) %>%
    select(Variable, Missing:p)


  ## fix in order to use escape = TRUE
  if (!addoverall) {colnames(tab1) <- sanitize_text(c(
    "Variables", "Missing (%)", levels(data %>% pull(!!sym(stratavar))), "p-value"
  ))}
  if (addoverall) {colnames(tab1) <- sanitize_text(c(
    "Variables", "Missing (%)", "Overall", levels(data %>% pull(!!sym(stratavar))), "p-value"
  ))}

  footnote(
    default_kable(tab1,
      font_size = 6,
      caption = paste0("Baseline characteristics ", tabname),
      longtable = TRUE,
      escape = FALSE
    ) %>%
      landscape(),
    general = c(
      "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
    ),
    symbol = c(
      "Included in the multiple imputation model (althought not necessarily imputed if there is no missing data) and logistic/cox models. FCM is included only in the consistency analyses.",
      "Medium within index year",
      "Medium within EF",
      "Missing is for patients with indexyear <= 2016 and >= 2017 respectively"
    )
  )
}
```

```{r tab1full, cache=cacheon, dependson="tab1"}
tab1func(data = rsdata, stratavar = "shf_ef_cat", tabname = "by EF - Full population", xlsname = "fullpopef")
```

```{r tab1aid, cache=cacheon, dependson="tab1"}
tab1func(data = rsdatalab, stratavar = "scream_aid", tabname = "by ID/A - Iron population", xlsname = "ida")
```

```{r tab1aidref, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_ef_cat == "HFrEF"), "scream_aid", "by ID/A -  Iron population HFrEF", xlsname = "ida_ref")
```

```{r tab1aidmref, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_ef_cat == "HFmrEF"), "scream_aid", "by ID/A - Iron population HFmrEF", xlsname = "ida_mref")
```

```{r tab1aidpef, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_ef_cat == "HFpEF"), "scream_aid", "by ID/A - Iron population HFpEF", xlsname = "ida_pef")
```

```{r tab1id, cache=cacheon, dependson="tab1"}
tab1func(data = rsdatalab, stratavar = "scream_id", tabname = "by ID - Iron population", xlsname = "id", addoverall = T)
```

```{r tab1idref, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_ef_cat == "HFrEF"), "scream_id", "by ID - Iron population HFrEF", xlsname = "id_ref")
```

```{r tab1idmref, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_ef_cat == "HFmrEF"), "scream_id", "by ID - Iron population HFmrEF", xlsname = "id_mref")
```

```{r tab1idpef, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_ef_cat == "HFpEF"), "scream_id", "by ID - Iron population HFpEF", xlsname = "id_pef")
```

```{r tab1idindex6mo, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(!is.na(scream_id6mo)), "scream_id_index6mo", "by ID at index and 6 mo", xlsname = "idindex6mo")
```

```{r tab1idinpat, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_location == "In-patient"), "scream_id", "by ID In-patients - Iron population", xlsname = "id_inpat")
```

```{r tab1idoutpat, cache=cacheon, dependson="tab1"}
tab1func(rsdatalab %>% filter(shf_location == "Out-patient"), "scream_id", "by ID Out-patients - Iron population", xlsname = "id_outpat")
```

```{r tab1fullid, cache=cacheon, dependson="tab1"}
rsdata <- rsdata %>%
  mutate(ironpop = factor(if_else(is.na(scream_id), "No", "Yes")))
tab1func(data = rsdata, stratavar = "ironpop", tabname = "by Iron population - Full population", xlsname = "fullpopiron", addoverall = T)
```

```{r tab1screened6mo, cache=cacheon, dependson="tab1"}
rsdatalab <- rsdatalab %>%
  mutate(scream_aid6mo_exist = factor(if_else(is.na(scream_aid6mo), "No", "Yes")))
tab1func(data = rsdatalab, stratavar = "scream_aid6mo_exist", tabname = "by repeated iron analyses at 6 mo - Iron population", xlsname = "repiron6mo")
```

```{r tab1screened1yr, cache=cacheon, dependson="tab1"}
rsdatalab <- rsdatalab %>%
  mutate(scream_aid1yr_exist = factor(if_else(is.na(scream_aid1yr), "No", "Yes")))
tab1func(data = rsdatalab, stratavar = "scream_aid1yr_exist", tabname = "by repeated iron analyses at 12 mo - Iron population", xlsname = "repiron12mo")
```